**Numpy:**

**Using NumPy create random vector of size 15 having only Integers in the range 1-20.**

In [1]:
import numpy as np

In [2]:
vector = np.random.randint(1, 20, 15, int)
print("Random vector is : ", vector)

Random vector is :  [ 9 10 18 18 19  1 15 16  3  9 11 13 14 13 15]


**1. Reshape the array to 3 by 5**

In [3]:
reshape_vector = np.reshape(vector, (3, 5))
print("\nReshaped array of size 3*5: \n", reshape_vector)


Reshaped array of size 3*5: 
 [[ 9 10 18 18 19]
 [ 1 15 16  3  9]
 [11 13 14 13 15]]


**2. Print array shape**

In [4]:
reshape_vector.shape

(3, 5)

**3. Replace the max in each row by 0**

In [5]:
print('\nPrint the matrix after replacing max in each row by 0: \n',
      np.where(reshape_vector == np.max(reshape_vector, axis=1).reshape((-1, 1)), 0, reshape_vector))


Print the matrix after replacing max in each row by 0: 
 [[ 9 10 18 18  0]
 [ 1 15  0  3  9]
 [11 13 14 13  0]]


**4. Extract a diagonal from the array and save it as .npy file format.**

In [6]:
print("\nDiagonal elements: ", np.diagonal(reshape_vector))
np.savetxt("output.npy", np.diag(reshape_vector))


Diagonal elements:  [ 9 15 14]
